repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
    -   id: check-added-large-files
    -   id: check-builtin-literals
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: fix-byte-order-marker
    -   id: sort-simple-yaml
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: master
    hooks:
    -   id: mypy
-   repo: https://github.com/pycqa/isort
    rev: master
    hooks:
    -   id: isort
-   repo: https://github.com/ambv/black
    rev: master
    hooks:
    -   id: black
        args: [--line-length=100]
-   repo: https://gitlab.com/pycqa/flake8
    rev: master
    hooks:
    -   id: flake8
        args: ["--max-line-length", "100", "--ignore", "E203,W503"]
